export const API_ENDPOINTS = {
  AUTH: {
    SEND_OTP: '/api/auth/send-otp',
    VERIFY_OTP: '/api/auth/verify-otp',
    COMPLETE_SIGNUP: '/api/auth/complete-signup',
    RESET_PASSWORD: '/api/auth/reset-password',
    LOGIN: '/api/auth/login',
    GOOGLE: '/api/auth/google',
    GITHUB: '/api/auth/github',
    REFRESH: '/api/auth/refresh',
    LOGOUT: '/api/auth/logout',
  },
  PROBLEMS: '/api/problems',
  QUIZZES: '/api/quizzes',
  PROFILE: '/api/profile',
  COURSES: '/api/courses',
  LECTURES: '/api/lectures',
  ENROLLMENTS: '/api/enrollments',
  PAYMENT: '/api/payment',
  NOTES: '/api/notes',
  FEEDBACK: '/api/feedback',
  SUBMISSIONS: '/api/submissions',
  RUN: '/api/compiler/run',
} as const;
